![imagen](../../imagenes/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1

1. Crea un array de una dimensión que vaya del 1 al 10 (incluidos) y llámalo ``array_1``
2. Crea un array de una dimensión, con 2001 valores equidistantes y que vaya desde -10 a 10 y llámalo ``array_2``
3. Convierte ``array_1`` en una matriz bidimensional de tamaño 2x5
4. Convierte ``array_2`` en una matriz tridimensional del tamaño que quieras, siempre y cuando todas las dimensiones tengan + de 1 valor y se mantengan todos los números que están en array_2


In [7]:
#1. 
array_1 = np.arange(1, 11)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#2. 
array_2 = np.linspace(-10, 10, 2001)
array_2

array([-10.  ,  -9.99,  -9.98, ...,   9.98,   9.99,  10.  ])

In [9]:
# 3.
array_1.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
# 4.
array_2.reshape(3, 23, 29)

array([[[-10.  ,  -9.99,  -9.98, ...,  -9.74,  -9.73,  -9.72],
        [ -9.71,  -9.7 ,  -9.69, ...,  -9.45,  -9.44,  -9.43],
        [ -9.42,  -9.41,  -9.4 , ...,  -9.16,  -9.15,  -9.14],
        ...,
        [ -4.2 ,  -4.19,  -4.18, ...,  -3.94,  -3.93,  -3.92],
        [ -3.91,  -3.9 ,  -3.89, ...,  -3.65,  -3.64,  -3.63],
        [ -3.62,  -3.61,  -3.6 , ...,  -3.36,  -3.35,  -3.34]],

       [[ -3.33,  -3.32,  -3.31, ...,  -3.07,  -3.06,  -3.05],
        [ -3.04,  -3.03,  -3.02, ...,  -2.78,  -2.77,  -2.76],
        [ -2.75,  -2.74,  -2.73, ...,  -2.49,  -2.48,  -2.47],
        ...,
        [  2.47,   2.48,   2.49, ...,   2.73,   2.74,   2.75],
        [  2.76,   2.77,   2.78, ...,   3.02,   3.03,   3.04],
        [  3.05,   3.06,   3.07, ...,   3.31,   3.32,   3.33]],

       [[  3.34,   3.35,   3.36, ...,   3.6 ,   3.61,   3.62],
        [  3.63,   3.64,   3.65, ...,   3.89,   3.9 ,   3.91],
        [  3.92,   3.93,   3.94, ...,   4.18,   4.19,   4.2 ],
        ...,
        [  9

## Ejercicio 2

Para hacer el ejercicio anterior, te habrás dado cuenta que no todas las combinaciones son válidas. Evidentemente, sólo podrás hacer la combinatoria de aquellos números que sean factores del número total de elementos.

1. Crea una función para obtener todos los factores enteros de un número entero. Deberá devolver una lista.
  - Ejemplo: si le pasas el 10, te tendrá que devolver una lista con [10, 5, 2, 1]
2. Crea otra función que reciba una array de numpy y una serie de números, y que devuelva 

In [33]:
def factores(x):
    l = []
    for i in range(x, 0, -1):
        if x%i == 0:
            l.append(i)
    return l

factores(10)


[10, 5, 2, 1]

In [27]:
np.array([10, 20, 30])%5

array([0, 0, 0], dtype=int32)

## Ejercicio 3

¿Te acuerdas de qué era el mínimo común múltiplo (mcm)? ¿Y el máximo común divisor (mcd)?

Básicamente, el mcm de 2 números naturales es el número más pequeño que se puede obtener que sea divisible entre ambos. Por ejemplo, el mcm de 4 y 3 es 12, que coincide con 4x3, pero el mcm de 4 y 8 no es 24, sino 8, ya que 4x4=8x2=16. Intenta pensar cómo se puede calcular basándote en los factores de cada número.

En cuanto al máximo común divisor, es el mayor factor que tienen en común 2 números, es decir, el mayor número por el que pueden ser divididos los 2 números naturales que utilicemos. Por ejemplo, el mcd de 10 y 15 es 5, o el mcd de 65 y 78 es 13.

Crea una función para obtener el mcm y otra para obtener el mcd de 2 números, que recibirán ambas funciones como parámetros. Para implementar la segunda, ayúdate de la función creada en el ejercicio anterior.

In [43]:
def mcm(*args):
    n_max = max(args)
    for i in range(n_max, x*y+1):
        if i%x == 0 and i%y == 0:
            return i
    return x*y

mcm(30, 4)
    

60

In [49]:
def f(*args):
    print(np.array(args))

f(1, 4, 2)

[1 4 2]


In [46]:

x = 4
y = 8
fx = factores(x)
fy = factores(y)

# max([num for num in fx if num in fy])
max()

# Sacamos los factores quitando el máximo y el mínimo:



4

In [31]:
# define la función
def mcd(a, b):
	resto = 0
	while(b > 0):
		resto = b
		b = a % b
		a = resto
	return a
 
# solicitamos los dos números
num1 = int(input("Introduce el primer numero: "))
num2 = int(input("Introduce el segundo numero: "))
 
print("El máximo común divisor de ", num1," y ", num2," es ", mcd(num1, num2))

Introduce el primer numero:  65
Introduce el segundo numero:  78


El máximo común divisor de  65  y  78  es  13


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

## Ejercicio 8
Obtén la documentación acerca de la función `concatenate`

Utiliza esa función para concatenar los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

## Ejercicio 9
Haz lo mismo con los siguientes arrays, pero esta vez horizontamente. Usa el mismo comando que en el ejercicio anterior:

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

## Ejercicio 10
Encuentra todos los elementos en común entre ambas listas. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```