# Ejercicio 2: Regresión lineal con diabetes

Uno de los datasets que tiene sklearn para practicar nuestras técnicas de Machine Learning, está relacionado con la diabetes. Lo bueno de estos datasets es que ya suelen estar preparados y limpios para trabajar con ellos, además de incluir numerosas utilidades como información de sus propias variables.

Lo primero que deberemos de hacer es cargar el dataset, para lo cual podemos hacer lo sigueinte:

In [12]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()

Si le echamos un vistazo a lo que acabamos de cargar, observaremos que diabetes es un diccionario, donde tenemos tanto los datos de entrada al modelo (en forma de matriz), las etiquetas de estos datos e información útil como una descripción del propio dataset.

In [13]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

#### ¿Qué es ese key de DESCR?

Por lo visto, el dataset tiene su propia descripción. Imprime por pantalla la descripción del dataset haciendo uso de la clave "DESCR" del diccionario de diabetes. Usa la función ``print`` para que se formatee bien lo que veas por pantalla:

*Tip: Lee lo que imprimas*

In [14]:
print(diabetes['DESCR'])

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, T-Cells (a type of white blood cells)
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, thyroid stimulating hormone
      - s5      ltg, lamotrigine
      - s6      glu, blood sugar level

Note: Each of these 10 feature va

#### Basándote en la descripción que acabas de leer, responde:

1. ¿Cuántos atributos tenemos en el dataset? ¿ Qué significan?

1. ¿Cuál es la relación entre `diabetes['data']` y `diabetes['target']`?

1. ¿Cuántos registros tenemos en los datos?

In [15]:
'''
10 features
La variable target es la que tenemos que predecir, y se trata de una medida cuantitativa que se asocia a la enfermedad a un año vista
442 registros
'''

'\n10 features\nLa variable target es la que tenemos que predecir, y se trata de una medida cuantitativa que se asocia a la enfermedad a un año vista\n442 registros\n'

#### Bien, ahora explora qué tenemos en ``data``, así como en el ``target``

Scikit-learn está diseñado en su mayoría para recibir arrays bidimensionales de Numpy como entrada (aunque también puede aceptar dataframes de Pandas). Inspecciona la forma de `data` y `target`. Confirma que se corresponden con la descripción que se comenta anteriormente

In [16]:
diabetes['data']

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [17]:
diabetes['data'].shape

(442, 10)

In [18]:
diabetes['target']

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [19]:
diabetes['target'].shape

(442,)

## Entrando en acción: Construyendo el modelo

Los datos ya se han dividido en variables de predicción (*data*) y respuesta (*target*). Dada esta información, aplica lo que has aprendido anteriormente sobre la regresión lineal, utilizando el algoritmo al conjunto de datos de diabetes.

#### Comienza por importar el regresor lineal de `linear_model` de `sklearn`. 

In [20]:
from sklearn.linear_model import LinearRegression

#### Crea una nueva instancia del modelo de regresión lineal que te acabas de importar y llámalo `diabetes_model`.

In [21]:
diabetes_model = LinearRegression()

#### Ahora, separa en train y test

Los nombres de las variables serán `diabetes_data_train`, `diabetes_target_train`, `diabetes_data_test`, y `diabetes_target_test`, respectivamente. Usa los 20 últimos registros para test y el resto para train. No es lo que se suele hacer, salvo que haya una marcada componente temporal, pero esta vez lo haremos así para ver qué pasaría:

In [22]:
diabetes_data_train = diabetes['data'][:-20]
diabetes_target_train = diabetes['target'][:-20]
diabetes_data_test = diabetes['data'][-20:]
diabetes_target_test = diabetes['target'][-20:]

In [23]:
print(diabetes_data_train.shape)
print(diabetes_target_train.shape)
print(diabetes_data_test.shape)
print(diabetes_target_test.shape)

(422, 10)
(422,)
(20, 10)
(20,)


Haz un ``fit`` de los datos de entrenamiento y su etiqueta sobre el modelo que estás creando: `diabetes_model`. Imprime el término independiente y los coeficientes del modelo:

In [24]:
diabetes_model.fit(diabetes_data_train, diabetes_target_train)

LinearRegression()

In [25]:
print(diabetes_model.intercept_)
print(diabetes_model.coef_)

152.76430691633442
[ 3.03499549e-01 -2.37639315e+02  5.10530605e+02  3.27736980e+02
 -8.14131709e+02  4.92814588e+02  1.02848452e+02  1.84606489e+02
  7.43519617e+02  7.60951722e+01]


#### Inspeccionando los resultados

De los resultados que deberías haber obtenido algo que coincidiera con:

- La intersección es un número flotante.
- Los coeficientes son una matriz que contiene 10 números flotantes.

Este es el modelo de regresión lineal ajustado al conjunto de datos de entrenamiento.

#### Usando el modelo de regresión lineal ajustado que te has creado, ¿podrías predecir el target de `diabetes_data_test`?


In [26]:
diabetes_model.predict(diabetes_data_test)

array([197.61846908, 155.43979328, 172.88665147, 111.53537279,
       164.80054784, 131.06954875, 259.12237761, 100.47935157,
       117.0601052 , 124.30503555, 218.36632793,  61.19831284,
       132.25046751, 120.3332925 ,  52.54458691, 194.03798088,
       102.57139702, 123.56604987, 211.0346317 ,  52.60335674])

#### Imprime el `diabetes_target_test` y compara con tus predicciones para eso mismo

In [27]:
diabetes_target_test

array([233.,  91., 111., 152., 120.,  67., 310.,  94., 183.,  66., 173.,
        72.,  49.,  64.,  48., 178., 104., 132., 220.,  57.])

In [28]:
diabetes_target_test - diabetes_model.predict(diabetes_data_test)

array([ 35.38153092, -64.43979328, -61.88665147,  40.46462721,
       -44.80054784, -64.06954875,  50.87762239,  -6.47935157,
        65.9398948 , -58.30503555, -45.36632793,  10.80168716,
       -83.25046751, -56.3332925 ,  -4.54458691, -16.03798088,
         1.42860298,   8.43395013,   8.9653683 ,   4.39664326])

#### Finalmente, calcula las métricas de lo que acabas de obtener. Saca los indicadores MAE, RMSE y R-squared

In [29]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

predict = diabetes_model.predict(diabetes_data_test)

print("RMSE:", np.sqrt(mean_squared_error(diabetes_target_test, predict)))
print("MAE:", mean_absolute_error(diabetes_target_test, predict))

RMSE: 44.772397776864956
MAE: 36.61017556715885
