# Repaso NumPy

![imagen](../../imagenes/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1

1. Crea un array de una dimensión que vaya del 1 al 10 (incluidos) y llámalo ``array_1``
2. Crea un array de una dimensión, con 2001 valores equidistantes y que vaya desde -10 a 10 y llámalo ``array_2``
3. Convierte ``array_1`` en una matriz bidimensional de tamaño 2x5
4. Convierte ``array_2`` en una matriz tridimensional del tamaño que quieras, siempre y cuando todas las dimensiones tengan + de 1 valor y se mantengan todos los números que están en array_2


In [11]:
array_1 = np.arange(1, 11)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
array_2 = np.linspace(-10, 10, 2001)
array_2

array([-10.  ,  -9.99,  -9.98, ...,   9.98,   9.99,  10.  ])

In [17]:
array_1.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Ejercicio 2

Para hacer el ejercicio anterior, te habrás dado cuenta que no todas las combinaciones son válidas. Evidentemente, sólo podrás hacer la combinatoria de aquellos números que sean factores del número total de elementos.

1. Crea una función para obtener todos los factores natural de un número natural. Deberá devolver una lista.
  - Ejemplo: si le pasas el 10, te tendrá que devolver una lista con [10, 5, 2, 1]
2. Crea otra función que reciba un array de NumPy (de las dimensiones que sean), y que imprima por pantalla las posibles combinaciones de 3 dimensiones.
  - Ejemplo: si nos pasan una matriz de 2x13, tendríamos que imprimir estas combinaciones:
    - 13 x 1 x 2
    - 2 x 13 x 1
    - 26 x 1 x 1
    - 13 x 2 x 1
    - 1 x 13 x 2
    - 1 x 26 x 1
    - 1 x 1 x 26
    - 2 x 1 x 13
    - 1 x 2 x 13
3. Crea otra versión de la función anterior para que solo imprima aquellas combinaciones que tengan todas sus dimensiones mayores que 1, imitando lo que pedía el último apartado del ejercicio anterior, y úsala para resolverlo.

In [23]:
# 1.
def divisores(numero):
    lista = []
    for i in range(numero, 0, -1):
        if numero % i == 0:
            lista.append(i)
        
    return(lista)

divisores(15)

[15, 5, 3, 1]

In [34]:
# 2.
def combinaciones(matriz):
    
    s = matriz.size
    combinaciones = []
    
    posibles_combinaciones = divisores(s)
    
    for i in posibles_combinaciones:
        for j in posibles_combinaciones:
            for k in posibles_combinaciones:
                if i*j*k == s:
                    combinaciones.append(f"{i} x {j} x {k}")
    return combinaciones

print(combinaciones(array_2))

['2001 x 1 x 1', '667 x 3 x 1', '667 x 1 x 3', '87 x 23 x 1', '87 x 1 x 23', '69 x 29 x 1', '69 x 1 x 29', '29 x 69 x 1', '29 x 23 x 3', '29 x 3 x 23', '29 x 1 x 69', '23 x 87 x 1', '23 x 29 x 3', '23 x 3 x 29', '23 x 1 x 87', '3 x 667 x 1', '3 x 29 x 23', '3 x 23 x 29', '3 x 1 x 667', '1 x 2001 x 1', '1 x 667 x 3', '1 x 87 x 23', '1 x 69 x 29', '1 x 29 x 69', '1 x 23 x 87', '1 x 3 x 667', '1 x 1 x 2001']


In [43]:
# 3.
def combinaciones_v2(matriz):
    
    s = matriz.size
    combinaciones = []
    posibles_combinaciones = divisores(s)[:-1]
    
    for i in posibles_combinaciones:
        for j in posibles_combinaciones:
            for k in posibles_combinaciones:
                if i*j*k == s:
                    combinaciones.append(f"""{i} x {j} x {k}""")
    return combinaciones

for i in combinaciones_v2(array_2):
    print(i)

29 x 23 x 3
29 x 3 x 23
23 x 29 x 3
23 x 3 x 29
3 x 29 x 23
3 x 23 x 29


## Ejercicio 3

¿Te acuerdas de qué era el mínimo común múltiplo (mcm)? ¿Y el máximo común divisor (mcd)?

Básicamente, el mcm de 2 números naturales es el número más pequeño que se puede obtener que sea divisible entre ambos. Por ejemplo, el mcm de 4 y 3 es 12, que coincide con 4x3, pero el mcm de 4 y 8 no es 24, sino 8, ya que 4x4=8x2=16. Intenta pensar cómo se puede calcular basándote en los factores de cada número.

En cuanto al máximo común divisor, es el mayor factor que tienen en común 2 números, es decir, el mayor número por el que pueden ser divididos los 2 números naturales que utilicemos. Por ejemplo, el mcd de 10 y 15 es 5, o el mcd de 65 y 78 es 13.

1. Crea una función para obtener el mcm y otra para obtener el mcd de 2 números, que recibirán ambas funciones como parámetros. Para implementar la segunda, ayúdate de la función creada en el ejercicio anterior.
2. Créate otras 2 nuevas funciones como las anteriores pero modificándolas para que puedan recibir más de 2 números como entrada. Puedes hacerlo recibiendo como parámetro de entrada una lista de dimensión desconocida, aunque también se podría hacer con *args (que podrías convertir a array según lo recibes).

NOTA: existe una función de NumPy que permite obtener el prducto de todos los elementos de una matriz: ``np.product(array)``

In [84]:
def mcm(num1, num2):
    for i in range(max(num1, num2), ((num1 * num2) + 1)):
        if i % num1 == 0 and i % num2 == 0: 
            return i

mcm(8, 4)

8

In [86]:
def mcd(num1, num2):
    for i in range(min(num1, num2), 0, -1):
        if num1 % i == 0 and num2 % i == 0: 
            return i

mcd(30, 15)

15

In [94]:
def mcd_2(num1, num2):
    d1 = divisores(num1)
    d2 = divisores(num2)
    return max(set(d1).intersection(set(d2)))

mcd_2(30, 15)

15

In [106]:
from collections import Counter

def mcml(x):
    x=np.array(x)
    multiplos=[]
    multiplos_c =[]
    
    for i in range(len(x)):
        for j in range(int(np.product(x)/x[i])):
            multiplos.append(x[i]*(j+1))
            
    c = Counter(multiplos)
    for i, j in c.items():
        if j==len(x):
            multiplos_c.append(i)
    print(min(multiplos_c))
    
mcml([6,8,56,84])

168


In [129]:
def mcm(*args):
    x = np.array(args)

    for j in range(max(x), np.product(x) + 1):
        if all(j%x == 0):
            return j
    
mcm(6,8,56,84) 

168

In [125]:
def mcdl(x):
    x=np.array(x)
    divisores=[]
    divisores_c =[]
    for i in range(len(x)):
        for j in range(max(x)):
            if x[i]%(j+1)==0:
                divisores.append(j+1)
                
    d=Counter(divisores)
    for i, j in d.items():
        if j==len(x):
            divisores_c.append(i)
    print(max(divisores_c))
    
mcdl([65,78,130])

13


In [130]:
def mcd(*args):
    x = np.array(args)

    for j in range(min(x), 0, -1):
        if all(x%j==0):
            return j
    
mcd(65,78,130)

13

## Ejercicio 4

Con una semilla de 10:

1. Crea un array bidimensional de 10 x 20 con números enteros aleatorios entre 1 y 10, y llámalo ``array``
2. Calcula la suma de todos los números de la matriz
3. Calcula la media de cada fila
4. Saca el máximo de cada columna
5. Crea una nueva matriz a partir de la matriz ``array`` pero cambiando los 5 por 10
6. Crea otra matriz a partir de ``array`` cuyos valores sean 1 si el valor original es mayor que 8 y 0 si no
7. Obtén una nueva matriz ``array_2`` que tenga las filas y columnas pares de ``array``. Entendiendo por pares la fila/columna 0, 2, 4...
8. Obtén una nueva matriz ``array_3`` que tenga las filas y columnas impares de ``array``
9. Crea una nueva matriz ``array_4`` como la concatenación horizontal de ``array_2`` y ``array_3``
10. Crea una nueva matriz ``array_5`` como la concatenación vertical de ``array_2`` y ``array_3``
11. Concatena ``array_4`` consigo mismo y llámalo ``array_6``. Concatena ``array_5`` consigo mismo y llámalo ``array_7``. Realiza estas operaciones para obtener un par de matrices del mismo tamaño 
12. Realiza la suma de ``array_6`` y ``array_7``. Realiza la división de todos los elementos de la matriz entre 5 y quédate con la parte entera (puedes hacerlo a tu manera o aprovechar que existe una función de numpy para conjuntos de números). Cambia el tipo de la matriz a int.


## Ejercicio 5

Utiliza la función np.arange() para generar una colección de números de 1 hasta 100 y, mediante slicing, filtrado y/o alguna operación aritmética, obtén las siguientes series:

1. [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

2. [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]

3. [11, 13, 15, 17, 19]

4. [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

5. [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]

6. [ 4, 16, 36, 64]

7. [97, 79, 67, 53, 41, 29, 17, 7, 2]

8. [100,  64,  36,  16,   4]


Ahora utiliza la función de generación de vectores más apropiada para:

9. [-5.5, -4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5]

10. [-2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75, 2.  ,  2.25]

11. Serie de 50 puntos desde 0 a 50 (ambos incluidos):

  [0., 0.10204082, 0.20408163, 0.30612245, 0.40816327, 0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735, 1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143, 1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551, 2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959, 2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367, 3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776, 3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184, 4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592, 4.59183673, 4.69387755, 4.79591837, 4.89795918, 5. ]


In [149]:
a = np.arange(1, 101)
a[np.sqrt(a)-np.array(np.sqrt(a), np.int32)==0]

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Ejercicio 6

Ahora vamos a intentar generar series un tanto más complejas, para lo que utilizaremos todo lo que veamos necesario, como bucles condicionales...:

1. Serie Fibonacci:
  Tomando como variables iniciales a=0 y b=1, piensa cómo obtener (y si no quieres pensar o no lo ves, busca por Internet):
    - [1, 2, 3, 5, 8, 13, 21]
    
2. Serie números primos entre 1 y 100 (si quieres, puedes ayudarte de la función factores del ejercicio 2):
  - [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
  
  
3. Progresión geométrica basada en Fibonacci:
  - [1, 2, 2, 4, 8, 32, 256]


## Ejercicio 7

Crea una función que reciba como argumento un array y que imprima por pantalla la siguiente info:
1. Nº de dimensiones del array
2. Forma del array
3. Nº elementos totales
4. Suma de todos los elementos
5. Máximo del array
6. Mínimo del array
7. Media por columna
8. Media por fila
9. Desviación típica por columna
10. Desviación típica por fila


## Ejercicio 8

Partiendo del siguiente array:


In [328]:
np.random.seed(10)
array = np.random.randint(1, 11, size = (10, 10))
array

array([[10,  5,  1,  2, 10,  1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1,  5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6,  4, 10,  7, 10,  2],
       [10,  5,  3,  7,  8,  9,  9, 10,  3,  1],
       [ 7,  8,  9,  2,  8,  2,  5,  1,  9,  6],
       [ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7],
       [ 7,  6,  7,  1,  1,  7, 10,  2,  9, 10],
       [ 2,  3,  9, 10, 10,  6,  1,  3,  8,  4],
       [ 1,  5,  3,  1,  4,  4,  2,  3,  6, 10],
       [ 1,  2,  1,  2, 10,  1, 10,  3,  2,  2]])

Obtén las siguientes matrices:
1. 


```Python
[[10,  1, 10,  2, 10],
 [ 5,  4,  6, 10, 10],
 [ 7,  9,  8,  5,  9],
 [ 7,  7,  1, 10,  9],
 [ 1,  3,  4,  2,  6]]
```

2. 


```Python
[[ 1,  2,  1,  2, 10,  1, 10,  3,  2,  2],
 [ 2,  3,  9, 10, 10,  6,  1,  3,  8,  4],
 [ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7],
 [10,  5,  3,  7,  8,  9,  9, 10,  3,  1],
 [ 9,  7,  5,  4,  1,  5,  7,  9,  2,  9]]
```

3. 


```Python
[[ 2,  2,  3, 10,  1, 10,  2,  1,  2,  1],
 [10,  6,  3,  2,  4,  4,  1,  3,  5,  1],
 [ 4,  8,  3,  1,  6, 10, 10,  9,  3,  2],
 [10,  9,  2, 10,  7,  1,  1,  7,  6,  7],
 [ 7,  9,  9,  3,  7,  3,  9,  9,  8,  5],
 [ 6,  9,  1,  5,  2,  8,  2,  9,  8,  7],
 [ 1,  3, 10,  9,  9,  8,  7,  3,  5, 10],
 [ 2, 10,  7, 10,  4,  6,  7,  4,  2,  5],
 [ 9,  2,  9,  7,  5,  1,  4,  5,  7,  9],
 [ 1, 10,  9,  2,  1, 10,  2,  1,  5, 10]]
```

4. 


```Python
[[ 9,  7,  5,  4,  1,  5,  7,  9,  2,  9],
 [ 5,  2,  4,  7,  6,  4, 10,  7, 10,  2],
 [ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7]]
```

## Ejercicio 9


1. Crea una función que reciba 2 numeros y cree una matriz de esas dimensiones donde los renglones impares sean 0 y los pares 1
2. Modifica la función anterior para que reciba otro parámetro booleano con el que se pueda especificar si "pintar" con 1 los renglones impares (True) o los pares (False). Recuerda que empezamos en la línea 0, por lo que el primer renglón se considera par.
3. Modifica la función anterior para que, en lugar de los renglones, pinte los marcos. En este caso, las matrices de entrada serán cuadradas.

In [ ]:


3, 3

111
101
111



6, 6

111111
100001
101101
101101
100001
111111



