# Repaso NumPy

![imagen](../../imagenes/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1

1. Crea un array de una dimensión que vaya del 1 al 10 (incluidos) y llámalo ``array_1``
2. Crea un array de una dimensión, con 2001 valores equidistantes y que vaya desde -10 a 10 y llámalo ``array_2``
3. Convierte ``array_1`` en una matriz bidimensional de tamaño 2x5
4. Convierte ``array_2`` en una matriz tridimensional del tamaño que quieras, siempre y cuando todas las dimensiones tengan + de 1 valor y se mantengan todos los números que están en array_2


In [3]:
#1. 
array_1 = np.arange(1, 11)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#2. 
array_2 = np.linspace(-10, 10, 2001)
array_2

array([-10.  ,  -9.99,  -9.98, ...,   9.98,   9.99,  10.  ])

In [5]:
# 3.
array_1.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
# 4.
array_2.reshape(3, 23, 29)

array([[[-10.  ,  -9.99,  -9.98, ...,  -9.74,  -9.73,  -9.72],
        [ -9.71,  -9.7 ,  -9.69, ...,  -9.45,  -9.44,  -9.43],
        [ -9.42,  -9.41,  -9.4 , ...,  -9.16,  -9.15,  -9.14],
        ...,
        [ -4.2 ,  -4.19,  -4.18, ...,  -3.94,  -3.93,  -3.92],
        [ -3.91,  -3.9 ,  -3.89, ...,  -3.65,  -3.64,  -3.63],
        [ -3.62,  -3.61,  -3.6 , ...,  -3.36,  -3.35,  -3.34]],

       [[ -3.33,  -3.32,  -3.31, ...,  -3.07,  -3.06,  -3.05],
        [ -3.04,  -3.03,  -3.02, ...,  -2.78,  -2.77,  -2.76],
        [ -2.75,  -2.74,  -2.73, ...,  -2.49,  -2.48,  -2.47],
        ...,
        [  2.47,   2.48,   2.49, ...,   2.73,   2.74,   2.75],
        [  2.76,   2.77,   2.78, ...,   3.02,   3.03,   3.04],
        [  3.05,   3.06,   3.07, ...,   3.31,   3.32,   3.33]],

       [[  3.34,   3.35,   3.36, ...,   3.6 ,   3.61,   3.62],
        [  3.63,   3.64,   3.65, ...,   3.89,   3.9 ,   3.91],
        [  3.92,   3.93,   3.94, ...,   4.18,   4.19,   4.2 ],
        ...,
        [  9

In [12]:
def f(x):
    y = x + 2
    return y

f(3)

5

## Ejercicio 2

Para hacer el ejercicio anterior, te habrás dado cuenta que no todas las combinaciones son válidas. Evidentemente, sólo podrás hacer la combinatoria de aquellos números que sean factores del número total de elementos.

1. Crea una función para obtener todos los factores enteros de un número entero. Deberá devolver una lista.
  - Ejemplo: si le pasas el 10, te tendrá que devolver una lista con [10, 5, 2, 1]
2. Crea otra función que reciba un array de NumPy (de las dimensiones que sean), y que imprima por pantalla las posibles combinaciones de 3 dimensiones.
  - Ejemplo: si nos pasan una matriz de 2x13, tendríamos que imprimir estas combinaciones:
    - 13 x 1 x 2
    - 2 x 13 x 1
    - 26 x 1 x 1
    - 13 x 2 x 1
    - 1 x 13 x 2
    - 1 x 26 x 1
    - 1 x 1 x 26
    - 2 x 1 x 13
    - 1 x 2 x 13
3. Crea otra versión de la función anterior para que solo imprima aquellas combinaciones que tengan todas sus dimensiones mayores que 1, imitando lo que pedía el último apartado del ejercicio anterior, y úsala para resolverlo.

In [24]:
def factores(x):
    l = []
    for i in range(x, 0, -np.sign(x)):
        if x%i == 0:
            l.append(i)
    return l

factores(10)

[10, 5, 2, 1]

In [22]:
def mat3shape(mat):
    # Sacamos los factores de la longitud de la matriz, para saber las posibles combinaciones que podremos hacer:
    f_mat = factores(mat.size)
    # Recorremos todas las posibles combinaciones y guardamos las que cumplan en una lista. Esto no es lo más eficiente, pero es una opción bastante sencilla:
    posibles_combinaciones = []
    print("Buscando posibles combinaciones...")
    for i in range(0, len(f_mat)):
        for j in range(0, len(f_mat)):
            for k in range(0, len(f_mat)):
                if f_mat[i]*f_mat[j]*f_mat[k] == mat.size:
                    posibles_combinaciones.append(f"{f_mat[i]} x {f_mat[j]} x {f_mat[k]}")

    if len(posibles_combinaciones) > 0:
        for combinacion in set(posibles_combinaciones):
            print(f"Posible combinación: {combinacion}")
    else:
        print("No se han encontrado combinaciones")
    
    return

mat = np.arange(1, 27).reshape(2, 13)
mat3shape(mat)

Buscando posibles combinaciones...
Posible combinación: 29 x 1 x 69
Posible combinación: 23 x 1 x 87
Posible combinación: 1 x 2001 x 1
Posible combinación: 1 x 1 x 2001
Posible combinación: 1 x 667 x 3
Posible combinación: 3 x 23 x 29
Posible combinación: 1 x 3 x 667
Posible combinación: 667 x 3 x 1
Posible combinación: 87 x 1 x 23
Posible combinación: 1 x 23 x 87
Posible combinación: 3 x 667 x 1
Posible combinación: 29 x 69 x 1
Posible combinación: 2001 x 1 x 1
Posible combinación: 23 x 3 x 29
Posible combinación: 87 x 23 x 1
Posible combinación: 667 x 1 x 3
Posible combinación: 69 x 1 x 29
Posible combinación: 1 x 29 x 69
Posible combinación: 23 x 29 x 3
Posible combinación: 23 x 87 x 1
Posible combinación: 29 x 23 x 3
Posible combinación: 3 x 29 x 23
Posible combinación: 69 x 29 x 1
Posible combinación: 1 x 69 x 29
Posible combinación: 29 x 3 x 23
Posible combinación: 1 x 87 x 23
Posible combinación: 3 x 1 x 667


In [93]:
def mat3shape_v2(mat):
    # Sacamos los factores de la longitud de la matriz, para saber las posibles combinaciones que podremos hacer:
    f_mat = factores(mat.size)
    # Recorremos todas las posibles combinaciones y guardamos las que cumplan en una lista. Esto no es lo más eficiente, pero es una opción bastante sencilla:
    posibles_combinaciones = []
    print("Buscando posibles combinaciones...")
    for i in range(0, len(f_mat)):
        for j in range(0, len(f_mat)):
            for k in range(0, len(f_mat)):
                if (f_mat[i]*f_mat[j]*f_mat[k] == mat.size) and ((f_mat[i] > 1 and f_mat[j] > 1 and f_mat[k] > 1)):
                    posibles_combinaciones.append(f"{f_mat[i]} x {f_mat[j]} x {f_mat[k]}")

    if len(posibles_combinaciones) > 0:
        for combinacion in set(posibles_combinaciones):
            print(f"Posible combinación: {combinacion}")
    else:
        print("No se han encontrado combinaciones")
    
    return

mat3shape_v2(array_2)

Buscando posibles combinaciones...
Posible combinación: 3 x 29 x 23
Posible combinación: 29 x 23 x 3
Posible combinación: 23 x 3 x 29
Posible combinación: 3 x 23 x 29
Posible combinación: 23 x 29 x 3
Posible combinación: 29 x 3 x 23


## Ejercicio 3

¿Te acuerdas de qué era el mínimo común múltiplo (mcm)? ¿Y el máximo común divisor (mcd)?

Básicamente, el mcm de 2 números naturales es el número más pequeño que se puede obtener que sea divisible entre ambos. Por ejemplo, el mcm de 4 y 3 es 12, que coincide con 4x3, pero el mcm de 4 y 8 no es 24, sino 8, ya que 4x4=8x2=16. Intenta pensar cómo se puede calcular basándote en los factores de cada número.

En cuanto al máximo común divisor, es el mayor factor que tienen en común 2 números, es decir, el mayor número por el que pueden ser divididos los 2 números naturales que utilicemos. Por ejemplo, el mcd de 10 y 15 es 5, o el mcd de 65 y 78 es 13.

1. Crea una función para obtener el mcm y otra para obtener el mcd de 2 números, que recibirán ambas funciones como parámetros. Para implementar la segunda, ayúdate de la función creada en el ejercicio anterior.
2. Créate otras 2 nuevas funciones como las anteriores pero modificándolas para que puedan recibir más de 2 números como entrada. Puedes hacerlo recibiendo como parámetro de entrada una lista de dimensión desconocida, aunque también se podría hacer con *args (que podrías convertir a array según lo recibes).

NOTA: existe una función de NumPy que permite obtener el prducto de todos los elementos de una matriz: ``np.product(array)``

In [122]:
def mcm(*args):
    vec = np.array(args)
    n_max = max(vec)
    for i in range(n_max, np.product(vec)):
        if all(i%vec == 0):
            return i
    return x*y

mcm(30, 4)    

60

In [123]:
# Version múltiple:
def mcm(*args):
    vec = np.array(args)
    n_max = max(vec)
    for i in range(n_max, np.product(vec)):
        if all(i%vec == 0):
            return i
    return x*y

mcm(30, 4)
    

60

In [124]:
def mcd(x, y):
    fx = factores(x)
    fy = factores(y)
    # Sacamos el máximo de los factores comunes, usando los sets y la intersección de los mismos:
    return max(set(fx).intersection(set(fy)))

mcd(20, 8)

4

In [125]:
# Version múltiple:
def mcd(*args):
    vec = np.array(args)
    f = set(factores(vec[0]))
    for i in vec[1:]:
        f = f.intersection(set(factores(i)))
    return max(f)

mcd(20, 8)

4

## Ejercicio 4

Con una semilla de 10:

1. Crea un array bidimensional de 10 x 20 con números enteros aleatorios entre 1 y 10, y llámalo ``array``
2. Calcula la suma de todos los números de la matriz
3. Calcula la media de cada fila
4. Saca el maximo de cada columna
5. Crea una nueva matriz a partir de la matriz ``array`` pero cambiando los 5 por 10
6. Crea otra matriz a partir de ``array`` cuyos valores sean 1 si el valor original es mayor que 8 y 0 si no
7. Obtén una nueva matriz ``array_2`` que tenga las filas y columnas pares de ``array``. Entendiendo por pares la fila/columna 0, 2, 4...
8. Obtén una nueva matriz ``array_3`` que tenga las filas y columnas impares de ``array``
9. Crea una nueva matriz ``array_4`` como la concatenación horizontal de ``array_2`` y ``array_3``
10. Crea una nueva matriz ``array_5`` como la concatenación vertical de ``array_2`` y ``array_3``
11. Concatena ``array_4`` consigo mismo y llámalo ``array_6``. Concatena ``array_5`` consigo mismo y llámalo ``array_7``. Realiza estas operaciones para obtener un par de matrices del mismo tamaño 
12. Realiza la suma de ``array_6`` y ``array_7``. Realiza la división de todos los elementos de la matriz entre 5 y quédate con la parte entera (puedes hacerlo a tu manera o aprovechar que existe una función de numpy para conjuntos de números). Cambia el tipo de la matriz a int.


In [164]:
# 1.
np.random.seed(10)
array = np.random.randint(1, 11, size=(10, 16))
array

array([[10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5],
       [ 7,  9,  2,  9,  5,  2,  4,  7,  6,  4, 10,  7, 10,  2, 10,  5],
       [ 3,  7,  8,  9,  9, 10,  3,  1,  7,  8,  9,  2,  8,  2,  5,  1],
       [ 9,  6,  5,  8,  9,  9,  3,  7,  3,  9,  9,  7,  7,  6,  7,  1],
       [ 1,  7, 10,  2,  9, 10,  2,  3,  9, 10, 10,  6,  1,  3,  8,  4],
       [ 1,  5,  3,  1,  4,  4,  2,  3,  6, 10,  1,  2,  1,  2, 10,  1],
       [10,  3,  2,  2,  1,  1,  6, 10,  1,  5,  7,  7,  1,  3,  4,  4],
       [ 3,  7,  1,  6,  2,  4,  7,  6,  6,  2,  9,  1,  6, 10,  9,  6],
       [ 8,  9,  6,  9, 10, 10,  2,  6, 10,  2,  5,  8,  8,  8, 10,  8],
       [ 7,  1,  4, 10,  5,  5,  7,  9,  5, 10,  3,  2,  2,  7,  4,  5]])

In [165]:
# 2.
array.sum()

886

In [166]:
# 3.
np.mean(array, axis=1)

array([5.125 , 6.1875, 5.75  , 6.5625, 5.9375, 3.5   , 4.1875, 5.3125,
       7.4375, 5.375 ])

In [167]:
# 4.
np.max(array, axis=0)

array([10,  9, 10, 10, 10, 10,  7, 10, 10, 10, 10,  8, 10, 10, 10,  8])

In [168]:
# 5.
np.where(array==5, 10, array)

array([[10, 10,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7, 10,  4,  1, 10],
       [ 7,  9,  2,  9, 10,  2,  4,  7,  6,  4, 10,  7, 10,  2, 10, 10],
       [ 3,  7,  8,  9,  9, 10,  3,  1,  7,  8,  9,  2,  8,  2, 10,  1],
       [ 9,  6, 10,  8,  9,  9,  3,  7,  3,  9,  9,  7,  7,  6,  7,  1],
       [ 1,  7, 10,  2,  9, 10,  2,  3,  9, 10, 10,  6,  1,  3,  8,  4],
       [ 1, 10,  3,  1,  4,  4,  2,  3,  6, 10,  1,  2,  1,  2, 10,  1],
       [10,  3,  2,  2,  1,  1,  6, 10,  1, 10,  7,  7,  1,  3,  4,  4],
       [ 3,  7,  1,  6,  2,  4,  7,  6,  6,  2,  9,  1,  6, 10,  9,  6],
       [ 8,  9,  6,  9, 10, 10,  2,  6, 10,  2, 10,  8,  8,  8, 10,  8],
       [ 7,  1,  4, 10, 10, 10,  7,  9, 10, 10,  3,  2,  2,  7,  4, 10]])

In [169]:
# 6.
np.where(array>8, 1, 0)

array([[1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0]])

In [184]:
# 7.
array_2 = array[::2, ::2]
array_2

array([[10,  1, 10,  2, 10,  9,  5,  1],
       [ 3,  8,  9,  3,  7,  9,  8,  5],
       [ 1, 10,  9,  2,  9, 10,  1,  8],
       [10,  2,  1,  6,  1,  7,  1,  4],
       [ 8,  6, 10,  2, 10,  5,  8, 10]])

In [185]:
# 8.
array_3 = array[1::2, 1::2]
array_3

array([[ 9,  9,  2,  7,  4,  7,  2,  5],
       [ 6,  8,  9,  7,  9,  7,  6,  1],
       [ 5,  1,  4,  3, 10,  2,  2,  1],
       [ 7,  6,  4,  6,  2,  1, 10,  6],
       [ 1, 10,  5,  9, 10,  2,  7,  5]])

In [190]:
# 9.
array_4 = np.hstack([array_2, array_3])
array_4

array([[10,  1, 10,  2, 10,  9,  5,  1,  9,  9,  2,  7,  4,  7,  2,  5],
       [ 3,  8,  9,  3,  7,  9,  8,  5,  6,  8,  9,  7,  9,  7,  6,  1],
       [ 1, 10,  9,  2,  9, 10,  1,  8,  5,  1,  4,  3, 10,  2,  2,  1],
       [10,  2,  1,  6,  1,  7,  1,  4,  7,  6,  4,  6,  2,  1, 10,  6],
       [ 8,  6, 10,  2, 10,  5,  8, 10,  1, 10,  5,  9, 10,  2,  7,  5]])

In [191]:
# 10.
array_5 = np.vstack([array_2, array_3])
array_5

array([[10,  1, 10,  2, 10,  9,  5,  1],
       [ 3,  8,  9,  3,  7,  9,  8,  5],
       [ 1, 10,  9,  2,  9, 10,  1,  8],
       [10,  2,  1,  6,  1,  7,  1,  4],
       [ 8,  6, 10,  2, 10,  5,  8, 10],
       [ 9,  9,  2,  7,  4,  7,  2,  5],
       [ 6,  8,  9,  7,  9,  7,  6,  1],
       [ 5,  1,  4,  3, 10,  2,  2,  1],
       [ 7,  6,  4,  6,  2,  1, 10,  6],
       [ 1, 10,  5,  9, 10,  2,  7,  5]])

In [200]:
# 11.
array_6 = np.vstack([array_4, array_4])
array_7 = np.hstack([array_5, array_5])
array_7.shape == array_6.shape

True

In [214]:
# 12.
array_8 = array_6 + array_7
array_8 = np.floor(array_8/5)

array_8 = np.array(array_8, 'int')
array_8

array([[4, 0, 4, 0, 4, 3, 2, 0, 3, 2, 2, 1, 2, 3, 1, 1],
       [1, 3, 3, 1, 2, 3, 3, 2, 1, 3, 3, 2, 3, 3, 2, 1],
       [0, 4, 3, 0, 3, 4, 0, 3, 1, 2, 2, 1, 3, 2, 0, 1],
       [4, 0, 0, 2, 0, 2, 0, 1, 3, 1, 1, 2, 0, 1, 2, 2],
       [3, 2, 4, 0, 4, 2, 3, 4, 1, 3, 3, 2, 4, 1, 3, 3],
       [3, 2, 2, 1, 2, 3, 1, 1, 3, 3, 0, 2, 1, 2, 0, 2],
       [1, 3, 3, 2, 3, 3, 2, 1, 2, 3, 3, 2, 3, 2, 2, 0],
       [1, 2, 2, 1, 3, 2, 0, 1, 2, 0, 1, 1, 4, 0, 0, 0],
       [3, 1, 1, 2, 0, 1, 2, 2, 2, 2, 1, 2, 0, 0, 4, 2],
       [1, 3, 3, 2, 4, 1, 3, 3, 0, 4, 2, 3, 4, 0, 2, 2]])

## Ejercicio 5

Utiliza la función np.arange() para generar una colección de números de 1 hasta 100 y, mediante slicing, filtrado y/o alguna operación aritmética, obtén las siguientes series:

1. [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

2. [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]

3. [11, 13, 15, 17, 19]

4. [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

5. [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]

6. [ 4, 16, 36, 64]

7. [99, 96, 93, 90, 87, 84, 81, 78, 75, 72, 69, 66, 63, 60, 57, 54, 51, 48, 45, 42, 39, 36, 33, 30, 27, 24, 21, 18, 15, 12,  9,  6,  3]

8. [100,  64,  36,  16,   4]


Ahora utiliza la función de generación de vectores más apropiada para:

9. [-5.5, -4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5]

10. [-2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75, 2.  ,  2.25]

11. Serie de 50 puntos desde 0 a 50 (ambos incluidos):

  [0., 0.10204082, 0.20408163, 0.30612245, 0.40816327, 0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735, 1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143, 1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551, 2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959, 2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367, 3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776, 3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184, 4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592, 4.59183673, 4.69387755, 4.79591837, 4.89795918, 5. ]


In [292]:
# 1.
l = np.arange(1, 100)
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [293]:
# 2.
l[::3]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [294]:
# 3.
l[10:20:2]

array([11, 13, 15, 17, 19])

In [295]:
# 4.
l[l%5==0]
# l[4::5]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [296]:
# 5.
l[:10]**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [297]:
# 6.
# l[np.sqrt(l)%2==0]
l[1:8:2]**2

array([ 4, 16, 36, 64], dtype=int32)

In [298]:
# 7.
l[::-3]

array([99, 96, 93, 90, 87, 84, 81, 78, 75, 72, 69, 66, 63, 60, 57, 54, 51,
       48, 45, 42, 39, 36, 33, 30, 27, 24, 21, 18, 15, 12,  9,  6,  3])

In [312]:
# 8.
l[9::-2]**2

array([100,  64,  36,  16,   4], dtype=int32)

In [283]:
# 9.
np.arange(-5.5, 5.5)

array([-5.5, -4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [285]:
# 10.
np.arange(-2.5, 2.5, 0.25)

array([-2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75, -0.5 ,
       -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,
        2.  ,  2.25])

In [287]:
# 11.
np.linspace(0, 5, 50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

## Ejercicio 6

Ahora vamos a intentar generar series un tanto más complejas, para lo que utilizaremos todo lo que veamos necesario, como bucles condicionales...:

1. Serie Fibonacci:
  Tomando como variables iniciales a=0 y b=1, piensa cómo obtener (y si no quieres pensar o no lo ves, busca por Internet):
    - [1, 2, 3, 5, 8, 13, 21]
    
2. Serie números primos entre 1 y 100 (si quieres, puedes ayudarte de la función factores del ejercicio 2):
  - [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
  
  
3. Progresión geométrica basada en Fibonacci:
  - [1, 2, 2, 4, 8, 32, 256]


In [269]:
# 1.
a = 0
b = 1

l = [a, b]

n_max = 21
z = b

while z < n_max:
    z = l[-2] + l[-1]
    l.append(z)
    
print(l)

[0, 1, 1, 2, 3, 5, 8, 13, 21]


In [282]:
# 2.
l = []
for i in range(2, 101):
    if len(factores(i)) <= 2:
        l.append(i)
print(l)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [279]:
factores(i)

[100, 50, 25, 20, 10, 5, 4, 2, 1]

In [270]:
# 3.
a = 1
b = 2

l = [a, b]

n_max = 100
z = b

while z < n_max:
    z = l[-2] * l[-1]
    l.append(z)
    
print(l)

[1, 2, 2, 4, 8, 32, 256]


## Ejercicio 7

Crea una función que reciba como argumento un array y que imprima por pantalla la siguiente info:
1. Nº de dimensiones del array
2. Forma del array
3. Nº elementos totales
4. Suma de todos los elementos
5. Máximo del array
6. Mínimo del array
7. Media por columna
8. Media por fila
9. Desviación típica por columna
10. Desviación típica por fila


## Ejercicio 8

Partiendo del siguiente array:


In [328]:
np.random.seed(10)
array = np.random.randint(1, 11, size = (10, 10))
array

array([[10,  5,  1,  2, 10,  1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1,  5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6,  4, 10,  7, 10,  2],
       [10,  5,  3,  7,  8,  9,  9, 10,  3,  1],
       [ 7,  8,  9,  2,  8,  2,  5,  1,  9,  6],
       [ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7],
       [ 7,  6,  7,  1,  1,  7, 10,  2,  9, 10],
       [ 2,  3,  9, 10, 10,  6,  1,  3,  8,  4],
       [ 1,  5,  3,  1,  4,  4,  2,  3,  6, 10],
       [ 1,  2,  1,  2, 10,  1, 10,  3,  2,  2]])

Obtén las siguientes matrices:
1. 


```Python
[[10,  1, 10,  2, 10],
 [ 5,  4,  6, 10, 10],
 [ 7,  9,  8,  5,  9],
 [ 7,  7,  1, 10,  9],
 [ 1,  3,  4,  2,  6]]
```

In [329]:
array[::2, ::2]

array([[10,  1, 10,  2, 10],
       [ 5,  4,  6, 10, 10],
       [ 7,  9,  8,  5,  9],
       [ 7,  7,  1, 10,  9],
       [ 1,  3,  4,  2,  6]])

2. 


```Python
[[ 1,  2,  1,  2, 10,  1, 10,  3,  2,  2],
 [ 2,  3,  9, 10, 10,  6,  1,  3,  8,  4],
 [ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7],
 [10,  5,  3,  7,  8,  9,  9, 10,  3,  1],
 [ 9,  7,  5,  4,  1,  5,  7,  9,  2,  9]]
```

In [331]:
array[::-2]

array([[ 1,  2,  1,  2, 10,  1, 10,  3,  2,  2],
       [ 2,  3,  9, 10, 10,  6,  1,  3,  8,  4],
       [ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7],
       [10,  5,  3,  7,  8,  9,  9, 10,  3,  1],
       [ 9,  7,  5,  4,  1,  5,  7,  9,  2,  9]])

3. 


```Python
[[ 2,  2,  3, 10,  1, 10,  2,  1,  2,  1],
 [10,  6,  3,  2,  4,  4,  1,  3,  5,  1],
 [ 4,  8,  3,  1,  6, 10, 10,  9,  3,  2],
 [10,  9,  2, 10,  7,  1,  1,  7,  6,  7],
 [ 7,  9,  9,  3,  7,  3,  9,  9,  8,  5],
 [ 6,  9,  1,  5,  2,  8,  2,  9,  8,  7],
 [ 1,  3, 10,  9,  9,  8,  7,  3,  5, 10],
 [ 2, 10,  7, 10,  4,  6,  7,  4,  2,  5],
 [ 9,  2,  9,  7,  5,  1,  4,  5,  7,  9],
 [ 1, 10,  9,  2,  1, 10,  2,  1,  5, 10]]
```

In [337]:
array[::-1, ::-1]

array([[ 2,  2,  3, 10,  1, 10,  2,  1,  2,  1],
       [10,  6,  3,  2,  4,  4,  1,  3,  5,  1],
       [ 4,  8,  3,  1,  6, 10, 10,  9,  3,  2],
       [10,  9,  2, 10,  7,  1,  1,  7,  6,  7],
       [ 7,  9,  9,  3,  7,  3,  9,  9,  8,  5],
       [ 6,  9,  1,  5,  2,  8,  2,  9,  8,  7],
       [ 1,  3, 10,  9,  9,  8,  7,  3,  5, 10],
       [ 2, 10,  7, 10,  4,  6,  7,  4,  2,  5],
       [ 9,  2,  9,  7,  5,  1,  4,  5,  7,  9],
       [ 1, 10,  9,  2,  1, 10,  2,  1,  5, 10]])

4. 


```Python
[[ 9,  7,  5,  4,  1,  5,  7,  9,  2,  9],
 [ 5,  2,  4,  7,  6,  4, 10,  7, 10,  2],
 [ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7]]
```

In [355]:
array[[1, 2, 5]]

array([[ 9,  7,  5,  4,  1,  5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6,  4, 10,  7, 10,  2],
       [ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7]])

## Ejercicio 9


1. Crea una función que reciba 2 numeros y cree una matriz de esas dimensiones donde los renglones impares sean 0 y los pares 1
2. Modifica la función anterior para que reciba otro parámetro booleano con el que se pueda especificar si "pintar" con 1 los renglones impares (True) o los pares (False). Recuerda que empezamos en la línea 0, por lo que el primer renglón se considera par.
3. Modifica la función anterior para que, en lugar de los renglones, pinte los marcos. En este caso, las matrices de entrada serán cuadradas.

In [360]:
# 1.
def renglones(x, y):
    array = np.zeros((x, y))
    array[::2] = 1
    return array

renglones(10, 12)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [365]:
# 2.
def renglones_2(x, y, impar=True):
    array = np.zeros((x, y))
    array[impar::2] = 1
    return array

renglones_2(10, 12, impar = False)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [521]:
# 3.
def rectangulo(x, impar):
    
    array = np.zeros((x, x))

    for i in range(impar, int(array.shape[1]/2)+1, 2):    
        array[array.shape[1]-1-i, i:array.shape[0]-i:] = 1
        array[i, i:array.shape[0]-i:] = 1
        array[i:array.shape[0]-i:, i] = 1
        array[i:array.shape[0]-i:, array.shape[0]-1-i] = 1

    return array

rectangulo(8, True)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 1., 0., 1., 0.],
       [0., 1., 0., 1., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])